[AutoRun]
enabled=false

[LegalNotice]
Accepted=true

[BitTorrent]
Session\AddTrackersEnabled=false
Session\AnnounceToAllTiers=true
Session\AnnounceToAllTrackers=true
Session\AnonymousModeEnabled=false
Session\DHTEnabled=false
Session\DefaultSavePath=/shared/qbittorrent
Session\DisableAutoTMMByDefault=true
Session\Encryption=2
Session\LSDEnabled=false
Session\PeXEnabled=true
Session\Port=6881
Session\TempPath=/shared/qbittorrent/incomplete
Session\TempPathEnabled=false
Session\UPnPEnabled=false

[Preferences]
Advanced\AnonymousMode=false
Bittorrent\DHT=false
Bittorrent\Encryption=2
Bittorrent\LSD=false
Bittorrent\PeX=true
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/shared/qbittorrent
Downloads\TempPathEnabled=false
General\Locale=en
WebUI\Address=*
WebUI\AuthSubnetWhitelist=0.0.0.0/0, ::/0
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWUTQob6IyJYsFDSfxsNUEJhNQdGChD3BWWK1NCdAT2ZbCCzycF3DMX3P/0NHnClC8ymP9qFP0lIQFw==)"
WebUI\Port=8080
WebUI\ServerDomains=*
WebUI\UseUPnP=false
WebUI\Username=admin
